title: Brick.Camp
metadata:
  description: 'The place to brick!'

author:
  name: Brick.Camp
  email: 'info@brick.camp'

taxonomies: 
  - tag
  - category
  - flag
  - source

  - part
  - partcount
  - tech

  - width
  - height
  - depth

  - function
  - object

  - pattern_segsize
  - pattern_1D_segsize
  - pattern_2D_segsize
  - pattern_3D_segsize

  - offset_length
  - stud_lift_length
  - stud_shift_length
  - axle_shift_length

  - rotation_angle
  - stud_tilt_angle
  - stud_twist_angle
  - axle_tilt_angle

  - shape_segments
  - shape_2D_segments
  - shape_3D_segments
  - shape_segsize
  - shape_2D_segsize
  - shape_3D_segsize
