title: BrickCamp

gitlab:
  url: 'https://gitlab.com/brick.camp/brick.camp'
  base: 'https://gitlab.com/brick.camp/brick.camp/tree/master/'
  license: 'README.md#license'

author:
  name: Brick.Camp
  email: 'info@brick.camp'

taxonomies: 
  - tag
  - category
  - flag
  - source

  - part
  - partcount
  - tech

  - width
  - height
  - depth

  - function
  - object
  - module_type

  - pattern_segsize
  - pattern_1D_segsize
  - pattern_2D_segsize
  - pattern_3D_segsize

  - offset_length
  - stud_lift_length
  - stud_shift_length
  - axle_shift_length

  - rotation_angle
  - stud_tilt_angle
  - stud_twist_angle
  - axle_tilt_angle

  - shape_segments
  - shape_2D_segments
  - shape_3D_segments
  - shape_segsize
  - shape_2D_segsize
  - shape_3D_segsize

redirects:
  '/../techs/with/(shape.*)': '/techs/shapes/$1'
  '/../techs/with/(.*angle.*)': '/techs/rotations/$1'
  '/../techs/with/(.*length.*)': '/techs/offsets/$1'
  '/../techs/with/(pattern.*)': '/techs/patterns/$1'
  '/../techs/using/part:(.+)': '/part/$1'