languages:
  supported: 
    - en
    - de
  http_accept_language: true

home:
  alias: '/home'
  hide_in_urls: true

pages:
  theme: brick-camp
  list:
    count: 12

  dateformat:
    default: null
    short: 'd-m-Y'
    long: 'd-m-Y G:i'
  markdown:
    extra: false
    auto_line_breaks: true
    auto_url_links: true
  expires: 604800
  cache_control: 3600
  ignore_folders: [.git, .idea, 00.drafts]

cache:
  enabled: true
  check:
    method: file
  gzip: true
  allow_webserver_gzip: true

twig:
  autoescape: false

assets:
  css_minify: false
  js_minify: false

errors:
  display: 1

debugger:
  enabled: true
  twig: true

images:
  auto_fix_orientation: false

session:
  enabled: false
  name: brickcamp