force_ssl: true
cache:
  enabled: true
twig:
  cache: true
  debug: false
  auto_reload: false
assets:
  css_pipeline: true
  css_minify: true
  css_minify_windows: false
  css_rewrite: true
  js_pipeline: true
  js_minify: true
  enable_asset_timestamp: true
errors:
  display: 1
  log: true
debugger:
  enabled: false
images:
  cache_all: false
  debug: false
gpm:
  releases: stable
  proxy_url: null
  method: auto
  verify_peer: true
  official_gpm_only: true
strict_mode:
  twig_compat: false